2022-01-03 22:57:15,492 INFO    MainThread:76746 [wandb_setup.py:_flush():71] setting env: {}
2022-01-03 22:57:15,492 INFO    MainThread:76746 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-03 22:57:15,492 INFO    MainThread:76746 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-03 22:57:15,492 INFO    MainThread:76746 [wandb_init.py:_log_setup():371] Logging user logs to /home/puppy/projects/BCI/wandb/run-20220103_225715-2e8z7cg4/logs/debug.log
2022-01-03 22:57:15,492 INFO    MainThread:76746 [wandb_init.py:_log_setup():372] Logging internal logs to /home/puppy/projects/BCI/wandb/run-20220103_225715-2e8z7cg4/logs/debug-internal.log
2022-01-03 22:57:15,492 INFO    MainThread:76746 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f98ec1a4e20>
2022-01-03 22:57:15,492 INFO    MainThread:76746 [wandb_init.py:init():404] calling init triggers
2022-01-03 22:57:15,493 INFO    MainThread:76746 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-03 22:57:15,493 INFO    MainThread:76746 [wandb_init.py:init():460] starting backend
2022-01-03 22:57:15,493 INFO    MainThread:76746 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-03 22:57:15,506 INFO    MainThread:76746 [backend.py:ensure_launched():216] starting backend process...
2022-01-03 22:57:15,518 INFO    MainThread:76746 [backend.py:ensure_launched():221] started backend process with pid: 76822
2022-01-03 22:57:15,519 INFO    MainThread:76746 [wandb_init.py:init():469] backend started and connected
2022-01-03 22:57:15,544 INFO    MainThread:76746 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-03 22:57:15,545 INFO    MainThread:76746 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-03 22:57:15,545 INFO    MainThread:76746 [wandb_init.py:init():533] updated telemetry
2022-01-03 22:57:15,549 INFO    MainThread:76746 [wandb_init.py:init():563] communicating current version
2022-01-03 22:57:20,550 INFO    MainThread:76746 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-03 22:57:21,689 INFO    MainThread:76746 [wandb_init.py:init():606] starting run threads in backend
2022-01-03 22:57:24,682 INFO    MainThread:76746 [wandb_run.py:_console_start():1810] atexit reg
2022-01-03 22:57:24,682 INFO    MainThread:76746 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-03 22:57:24,683 INFO    MainThread:76746 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-03 22:57:24,683 INFO    MainThread:76746 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-03 22:57:24,683 INFO    MainThread:76746 [wandb_init.py:init():633] run started, returning control to user process
2022-01-03 23:33:47,494 INFO    MainThread:76746 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-03 23:33:47,494 INFO    MainThread:76746 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-04 00:24:32,557 INFO    MainThread:76746 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-04 00:24:32,558 INFO    MainThread:76746 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-04 00:24:32,558 INFO    MainThread:76746 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-04 00:25:32,369 INFO    MainThread:76746 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-04 00:25:32,370 INFO    MainThread:76746 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-04 00:25:32,370 INFO    MainThread:76746 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-04 00:31:06,821 INFO    MainThread:76746 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-04 00:31:06,834 INFO    MainThread:76746 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-04 00:31:06,834 INFO    MainThread:76746 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-04 00:31:26,562 INFO    MainThread:76746 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-01-04 00:31:26,565 INFO    MainThread:76746 [wandb_run.py:_restore():1752] restore
